ML_Sys_Des_hw_1
MakArtKar/negotiations_trainer pull request #1
Opened 2024-11-28 15:20 UTC by MakArtKar

* Added [ML Design Doc](docs/ml_system_design_doc.md)
* Generated block scheme with PlantUML
* Pre-commit and linters
* Updated [README.md](./README.md)

2024-12-02 13:45 UTC, Vloods requested changes
### Чек-лист проверки выполнения задач

#### 1. Сетап репозитория проекта
- [x] Репозиторий подготовлен для работы:
  - [x] Настроены линтеры и форматеры (ruff, black).  
  - [x] Настроен pre-commit.  
  - [ ] Заполнен файл `README.md` с основной информацией о проекте.  

#### 2. Заполнение дизайн-документа
- [x] В репозитории создана папка `docs`.
- [x] В папке `docs` создан файл `ml_system_design_doc.md`.
- [x] В файле `ml_system_design_doc.md` заполнена следующая информация:
  - [x] Зачем идем в разработку продукта?  
  - [x] Бизнес-требования и ограничения.  
  - [x] Что входит в скоуп проекта/итерации, что не входит.  
  - [x] Предпосылки решения.  
  - [x] Постановка задачи.  
  - [x] Блок-схема решения.

2024-12-04 14:39 UTC, MakArtKar commented
> ### Чек-лист проверки выполнения задач
> #### 1. Сетап репозитория проекта
> * [x]  Репозиторий подготовлен для работы:
>   
>   * [x]  Настроены линтеры и форматеры (ruff, black).
>   * [x]  Настроен pre-commit.
>   * [ ]  Заполнен файл `README.md` с основной информацией о проекте.
> 
> #### 2. Заполнение дизайн-документа
> * [x]  В репозитории создана папка `docs`.
> * [x]  В папке `docs` создан файл `ml_system_design_doc.md`.
> * [x]  В файле `ml_system_design_doc.md` заполнена следующая информация:
>   
>   * [x]  Зачем идем в разработку продукта?
>   * [x]  Бизнес-требования и ограничения.
>   * [x]  Что входит в скоуп проекта/итерации, что не входит.
>   * [x]  Предпосылки решения.
>   * [x]  Постановка задачи.
>   * [x]  Блок-схема решения.

Спасибо, заполнил README, теперь там есть краткое описание проекта, а также QuickStart

2024-12-04 14:49 UTC, Vloods approved these changes

2024-12-04 22:31 UTC, danilovsnnv commented
### Чек-лист проверки выполнения задач

#### 1. Сетап репозитория проекта
- [x] Репозиторий подготовлен для работы:
  - [x] Настроены линтеры и форматеры (ruff, black).  
  - [x] Настроен pre-commit.  
  - [x] Заполнен файл `README.md` с основной информацией о проекте.  

#### 2. Заполнение дизайн-документа
- [x] В репозитории создана папка `docs`.
- [x] В папке `docs` создан файл `ml_system_design_doc.md`.
- [x] В файле `ml_system_design_doc.md` заполнена следующая информация:
  - [x] Зачем идем в разработку продукта?  
  - [x] Бизнес-требования и ограничения.  
  - [x] Что входит в скоуп проекта/итерации, что не входит.  
  - [x] Предпосылки решения.  
  - [x] Постановка задачи.  
  - [x] Блок-схема решения.  

### Комментарии

Все классно, README и дизайн документ хорошо написаны

2024-12-09 11:12 UTC, asesorov commented
В целом очень неплохой документ, добавить численные метрики - и будет супер

2024-12-09 11:15 UTC, asesorov commented
Еще не вижу настроенного прекоммита через github actions, линтер есть - его бы как раз туда закинуть

2024-12-09 11:37 UTC, MakArtKar commented
> В целом очень неплохой документ, добавить численные метрики - и будет супер

> Еще не вижу настроенного прекоммита через github actions, линтер есть - его бы как раз туда закинуть

@asesorov спасибо за фидбек. Добавил прекоммит через github actions, также добавил чуть больше численных метрик в критерии успеха.

2024-12-09 16:09 UTC, MakArtKar commented
> ### Чек-лист проверки выполнения задач
> #### 1. Сетап репозитория проекта
> * [x]  Репозиторий подготовлен для работы:
>   
>   * [x]  Настроены линтеры и форматеры (ruff, black).
>   * [x]  Настроен pre-commit.
>   * [x]  Заполнен файл `README.md` с основной информацией о проекте.
> 
> #### 2. Заполнение дизайн-документа
> * [x]  В репозитории создана папка `docs`.
> * [x]  В папке `docs` создан файл `ml_system_design_doc.md`.
> * [x]  В файле `ml_system_design_doc.md` заполнена следующая информация:
>   
>   * [x]  Зачем идем в разработку продукта?
>   * [x]  Бизнес-требования и ограничения.
>   * [x]  Что входит в скоуп проекта/итерации, что не входит.
>   * [x]  Предпосылки решения.
>   * [x]  Постановка задачи.
>   * [x]  Блок-схема решения.
> 
> ### Комментарии
> Все классно, README и дизайн документ хорошо написаны

@danilovsnnv кажется тебя все устраивает, можешь плз тогда

2024-12-10 08:46 UTC, asesorov commented on docs/images/block-scheme.png
Из картинки не совсем понятно, для чего нужны два агента в системе - у них одинаковый набор действий и описание

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +**Что будем считать успехом итерации с точки зрения бизнеса**
В качестве критериев успешности нужно добавить какие-либо количественные метрики - процент галлюцинаций, число удовлетворенных пользователей, а также уточнить, как именно будет оцениваться "Улучшение переговорных скилов"

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Разработка мультиагентного фреймворка для одновременного использования нескольких ML-агентов.
В бизнес-требованиях не совсем корректно указывать технические подробности (разработка, интеграция и т.д.) - необходимо указать конкретные бизнес-метрики, которые планируется улучшать - как продукт будет полезен бизнесу

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +**Бизнес-ограничения:**
Отличные ограничения, я бы еще добавил что-нибудь для обеспечения безопасности данных

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Отзывы пользователей для проверки корректности симуляций и моделей поведения агентов.
Как будете собирать отзывы? Внутри ТГ-бота или отдельным опросником?

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Реализация трех типов поведения ML-агентов: агрессивного, умеренного и избегающего.
> агрессивного, умеренного и избегающего.

Что подразумевается под этими типами? Как будет отличаться поведение агента?

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Несколько бизнес-кейсов с поддержкой "умеренного" типа поведения ML-агентов.
> Несколько бизнес-кейсов

Тут я бы конкретизировал и, возможно, сократил бы даже до одного

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Создание фреймворка для взаимодействия нескольких агентов.
По собственному фреймворку - тогда нужно обоснование, почему не планируете использовать существующие (я бы рекомендовал все-таки не разрабатывать свое решение с нуля)

2024-12-10 08:46 UTC, asesorov commented on docs/ml_system_design_doc.md
> +- Проверка корректности поведения агентов через тестовые сценарии.
Какие будут метрики оценки корректности поведения агентов? Возможно, интегрируете какие-нибудь опенсорсные берчмарки, по типу https://github.com/huggingface/evaluate?

2024-12-10 08:47 UTC, asesorov commented
Комменты выше вчера остались в pending, сегодня заметил и прожал их отправку, если что-то устарело - сорри) сегодня посмотрю изменения, вижу их

2024-12-11 11:09 UTC, MakArtKar commented on docs/images/block-scheme.png
Да, идея в том, что агенты заменяют реальных игроков в симуляции, отличаются они лишь тем, что у них разная роль/вводные/легенда, которая зависит от конкретного кейса. Также количество агентов может быть разным. Поэтому на схеме они идентичны.

2024-12-17 17:07 UTC, MakArtKar commented
> ### Чек-лист проверки выполнения задач
> #### 1. Сетап репозитория проекта
> * [x]  Репозиторий подготовлен для работы:
>   
>   * [x]  Настроены линтеры и форматеры (ruff, black).
>   * [x]  Настроен pre-commit.
>   * [x]  Заполнен файл `README.md` с основной информацией о проекте.
> 
> #### 2. Заполнение дизайн-документа
> * [x]  В репозитории создана папка `docs`.
> * [x]  В папке `docs` создан файл `ml_system_design_doc.md`.
> * [x]  В файле `ml_system_design_doc.md` заполнена следующая информация:
>   
>   * [x]  Зачем идем в разработку продукта?
>   * [x]  Бизнес-требования и ограничения.
>   * [x]  Что входит в скоуп проекта/итерации, что не входит.
>   * [x]  Предпосылки решения.
>   * [x]  Постановка задачи.
>   * [x]  Блок-схема решения.
> 
> ### Комментарии
> Все классно, README и дизайн документ хорошо написаны

@danilovsnnv кажется от тебя комментариев для исправление нету, если все ок - можешь плз проставить аппрув?

2024-12-17 17:11 UTC, MakArtKar reviewed
Большое спасибо за замечания - дополнил дизайн документ

2024-12-17 17:11 UTC, MakArtKar commented on docs/ml_system_design_doc.md
> +**Что будем считать успехом итерации с точки зрения бизнеса**
Критерии успеха с количественными метриками у меня собраны в конце документа, здесь представлена мотивация, почему мы хотим делать МЛ

2024-12-17 17:11 UTC, MakArtKar commented on docs/ml_system_design_doc.md
> +- Создание фреймворка для взаимодействия нескольких агентов.
Да, здесь планировалось сделать надстройку над существующим фреймворком - поправил

2024-12-17 17:11 UTC, MakArtKar commented on docs/ml_system_design_doc.md
> +- Проверка корректности поведения агентов через тестовые сценарии.
Тут идея, что мы хотим убедиться, что агент не несет чушь. Для этого будем собирать оценки пользователей на бета-тестировании + юнит тесты, которые будут проверять, что агент не предлагает нереалистичную сделку.

2025-01-11 17:12 UTC, danilovsnnv approved these changes

2025-01-13 19:30 UTC, merged